.github/workflows/crypto_box.yml, .github/workflows/crypto_secretstream.yml, .github/workflows/workspace.yml, Cargo.lock, Cargo.toml, crypto_box/Cargo.toml, crypto_secretstream/README.md, crypto_secretstream/src/stream.rs
Also transitively bumps MSRV to 1.51+
=> crypto_box: bump `chacha20poly1305` to v0.9; `xsalsa20poly1305` to v0.8

Cargo.lock, README.md, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml
- MSRV 1.51 ([#8])
- Bump `chacha20poly1305` to v0.9 ([#8])
- Bump `xsalsa20poly1305` to v0.8 ([#8])
[#8]: https://github.com/RustCrypto/nacl-compat/pull/8
=> crypto_box v0.7.0

crypto_box/CHANGELOG.md, crypto_box/src/lib.rs, crypto_box/tests/lib.rs
This is consistent with the API for PublicKey. If one wants to copy the
byte array, the slice can be dereferenced.
Closes #23.
=> crypto_box: Replace SecretKey::to_bytes with as_bytes

.github/workflows/crypto_box.yml
The crypto_box integration tests were gated on the `std` feature, which
was not enabled in CI. Thus none of these tests were actually run in CI.
=> CI: Actually run crypto_box tests

.github/workflows/crypto_box.yml, Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs
The `serde` feature is optional, but enabled by default. (Could be made off-by-default if desired, not sure if we have a batteries-included or a minimal-by-default policy here.)
I used the serde-crate-alias trick, inspired by https://github.com/RustCrypto/RSA/pull/41
For a round-trip serialization test, I added "bincode" and "rand" dev-dependencies.
=> crypto_box: Add optional serde support

crypto_box/src/lib.rs
We were missing a crate attribute for the doc_cfg feature. Without this, the docs on docs.rs cannot be built:
https://docs.rs/crate/crypto_box/0.7.1/builds/491318
To test this locally, this seems to do the trick:
cargo +nightly rustdoc --features serde -Z unstable-options --config 'build.rustdocflags=["--cfg", "docsrs"]'
=> Fix building on docs.rs

crypto_box/CHANGELOG.md
This was retroactively released as of the changes in #30. However, there are other changes on `master`, so this commit only includes the CHANGELOG.md entry.
The `crypto_box-v0.7.2` tag shows the commit history:
https://github.com/RustCrypto/nacl-compat/tree/crypto_box-v0.7.2
=> crypto_box: add v0.7.2 CHANGELOG.md entry

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_secretstream/Cargo.toml, crypto_secretstream/src/stream.rs
I'm not sure how the versioning should work for these crates, both are currently on -pre versions.
=> Update crypto_box, crypto_secretstream dependencies

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs
Replaces the handwritten serde visitor implementation with the same-shaped implementation in the `serdect` crate.
This reduces the maintenance burden of `serde`-related code, by keeping all of the complexity and interop testing in the `serdect` crate.
=> crypto_box: use `serdect` crate

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_box/tests/lib.rs
Activates crate features transitively through the `aead` crate
=> crypto_box: add direct `aead` dependency and use it for features

.cargo/audit.toml
`sodiumoxide` is unmaintained, however we still use it for interop testing
=> CI: fix security audit

.github/workflows/crypto_box.yml, crypto_box/Cargo.toml, crypto_box/src/lib.rs
Introspects the target pointer width to automatically select either the `u32_backend` or `u64_backend`.
If the backend isn't 32/64-bit, generate a compile error with an informative message.
Removes the explicit `u32_backend`/`u64_backend` crate features in `cargo_box` itself. Now `--all-features` works.
=> crypto_box: select `x25519-dalek` backend automatically

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml
- Unpin `zeroize` version ([#41])
- Upgrade to Rust 2021 edition; MSRV 1.56 ([#42])
- Bump `chacha20` to v0.9 ([#50])
- Bump `chacha20poly1305` to v0.10 ([#50])
- Use `serdect` crate ([#51])
- Select `x25519-dalek` backend automatically ([#55])
- `Box` type alias: use `SalsaBox` instead ([#53])
- `u32_backend` and `u64_backend` features: now selected automatically ([#55])
[#41]: https://github.com/RustCrypto/nacl-compat/pull/41
[#42]: https://github.com/RustCrypto/nacl-compat/pull/42
[#50]: https://github.com/RustCrypto/nacl-compat/pull/50
[#51]: https://github.com/RustCrypto/nacl-compat/pull/51
[#53]: https://github.com/RustCrypto/nacl-compat/pull/53
[#55]: https://github.com/RustCrypto/nacl-compat/pull/55
=> crypto_box v0.8.0

Cargo.lock, crypto_kx/Cargo.toml, crypto_kx/src/keypair.rs, crypto_kx/src/keys/public.rs, crypto_kx/src/keys/secret.rs, crypto_kx/src/lib.rs
Replaces the handwritten serde visitor implementation with the same-shaped implementation in the `serdect` crate, similar to the changes to the `crypto_box` crate in #51.
This reduces the maintenance burden of `serde`-related code, by keeping all of the complexity and interop testing in the `serdect` crate.
=> crypto_kx: use `serdect` crate

crypto_kx/Cargo.toml, crypto_kx/README.md, crypto_kx/src/lib.rs
Introspects the target pointer width to automatically select either the `u32_backend` or `u64_backend`, similar to #55.
If the backend isn't 32/64-bit, generate a compile error with an informative message.
=> crypto_kx: select `x25519-dalek` backend automatically

Cargo.lock, crypto_kx/CHANGELOG.md, crypto_kx/Cargo.toml
- Bump `blake2` to v0.10 ([#22])
- Upgrade to Rust 2021 edition; MSRV 1.56 ([#42])
- Use `serdect` crate ([#59])
- Select `x25519-dalek` backend automatically ([#60])
[#22]: https://github.com/RustCrypto/nacl-compat/pull/22
[#42]: https://github.com/RustCrypto/nacl-compat/pull/42
[#59]: https://github.com/RustCrypto/nacl-compat/pull/59
[#60]: https://github.com/RustCrypto/nacl-compat/pull/60
=> crypto_kx v0.1.0

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml
- Revert "select `x25519-dalek` backend automatically" ([#63])
[#63]: https://github.com/RustCrypto/nacl-compat/pull/63
=> crypto_box v0.8.1

crypto_box/README.md
Here's the updated README for the second crate that was part of the audit.
=> crypto_box: Mention audit in README

.github/dependabot.yml
Add Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.
=> extend Dependabot configuration to keep GitHub Actions up to date

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml
- `seal` and `seal_open` functions ([#66])
[#66]: https://github.com/RustCrypto/nacl-compat/pull/66
=> crypto_box v0.8.2

crypto_secretstream/src/stream.rs
`len()` returns a `usize` which causes a WASM build of crypto_secretstream to fail with:
```
source slice length (4) does not match destination slice length (8)', crypto_secretstream/src/stream.rs:101`
```
With the below patch this problem is fixed. I believe this should be quite safe to merge (but not a Rust expert by no means).
=> crypto_secretstream: Fix copy_with_slice expecting 8 bytes and WASM having 32bit usize 

Cargo.lock, crypto_secretstream/CHANGELOG.md, crypto_secretstream/Cargo.toml
- WASM problem with 32-bit usize and `copy_with_slice` expecting 8-bytes ([#76])
[#76]: https://github.com/RustCrypto/nacl-compat/pull/76
=> crypto_secretstream v0.1.1

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_secretbox/README.md
Sources `XSalsa20Poly1305` from `crypto_secretbox` instead of the `xsalsa20poly1305` crate.
The longer-term goal is to make `XSalsa20Poly1305` generic around the stream cipher.
=> crypto_box: use `crypto_secretbox`

crypto_box/src/lib.rs
In some situations it makes sense to use public keys as identifiers. In that case, it's useful to be able to sort a list of public keys (e.g. to print them in correct order for diagnostic purposes).
=> crypto_box: Derive Ord/PartialOrd for PublicKey

.github/workflows/crypto_box.yml, .github/workflows/crypto_kx.yml, .github/workflows/crypto_secretbox.yml, .github/workflows/crypto_secretstream.yml, .github/workflows/workspace.yml, Cargo.lock, crypto_box/Cargo.toml, crypto_box/README.md, crypto_box/src/lib.rs, crypto_box/tests/lib.rs, crypto_kx/Cargo.toml, crypto_kx/README.md, crypto_secretbox/Cargo.toml, crypto_secretbox/README.md, crypto_secretstream/Cargo.toml, crypto_secretstream/README.md
Upgrades to the latest `curve25519-dalek` v4.0.0-rc.1 release.
The `x25519-dalek` crate is a wrapper whose functionality isn't really used, and we can use the `Scalar` and `MontgomeryPoint` types directly.
=> crypto_box: use `curve25519-dalek`; MSRV 1.60

Cargo.lock, crypto_kx/Cargo.toml, crypto_kx/src/keypair.rs, crypto_kx/src/keys/public.rs, crypto_kx/src/keys/secret.rs, crypto_kx/src/lib.rs, crypto_kx/tests/lib.rs, crypto_kx/tests/sodiumoxide.rs
Upgrades to the latest `curve25519-dalek` v4.0.0-rc.1 release.
The `x25519-dalek` crate is a wrapper whose functionality isn't really used, and we can use the `Scalar` and `MontgomeryPoint` types directly and eliminate the extra dependency.
=> crypto_kx: use `curve25519-dalek`; MSRV 1.60

crypto_box/src/lib.rs, crypto_kx/Cargo.toml, crypto_kx/src/lib.rs, crypto_secretbox/src/lib.rs
Replace manual `doc(cfg(...))` annotations with automatic documentation generation.
=> Use `doc_auto_cfg`

.github/workflows/crypto_box.yml, .github/workflows/crypto_kx.yml, .github/workflows/crypto_secretbox.yml, .github/workflows/crypto_secretstream.yml, .github/workflows/workspace.yml
Replaces actions-rs, which is unmaintained
=> CI: use `dtolnay/rust-toolchain` to install Rust

Cargo.lock, crypto_box/Cargo.toml, crypto_secretbox/Cargo.toml, crypto_secretbox/src/lib.rs, crypto_secretbox/tests/xsalsa20poly1305.rs
The intent is to allow using it with `chacha20` exclusively if desired.
=> crypto_secretbox: make `salsa20` an optional dependency

.github/workflows/crypto_secretbox.yml, Cargo.lock, crypto_secretbox/Cargo.toml, crypto_secretbox/README.md, crypto_secretbox/src/lib.rs
Adds `chacha20` feature providing a `XChaCha20Poly1305` type alias.
Note that this construction of "XChaCha20Poly1305" is different from the one implemented by the `chacha20poly1305` crate, which implements constructions based on the IETF variant of ChaCha20Poly1305.
The flavor of `XChaCha20Poly1305` in this crate is based on pre-IETF constructions and is only supported by libsodium.
This is an unfortunate state of affairs to have two incompatible constructions with the same name. One of the original goals of `draft-irtf-cfrg-xchacha` was to ensure that "XChaCha20" was always based on the IETF variant of ChaCha20.
The `AEAD_XChaCha20_Poly1305` construction that I-D defines is only compatible with the version implemented by the `chacha20poly1305` crate, and is *INCOMPATIBLE* with the …
=> crypto_secretbox: add `chacha20` feature

Cargo.lock, crypto_secretbox/Cargo.toml, crypto_secretbox/src/lib.rs
Previously this was using the IETF variant of ChaCha20, but for compatibility with e.g. libsodium we need to use the original DJB variant.
This also changes to using the `Salsa20` (as opposed to `XSalsa20`) type and using the `Kdf` trait to impl both `XSalsa20` and `XChaCha20`, since the `chacha20` version of `XChaCha20` is built on the IETF variant of `ChaCha20` (so as to be compatible with draft-irtf-cfrg-xchacha).
=> crypto_secretbox: use `Salsa20` and `ChaCha20Legacy`

Cargo.lock, crypto_box/Cargo.toml, crypto_secretbox/CHANGELOG.md, crypto_secretbox/Cargo.toml
- Re-export `cipher` ([#113])
[#113]: https://github.com/RustCrypto/nacl-compat/pull/113
=> crypto_secretbox v0.1.1

crypto_box/src/lib.rs
`rand_core` is available as `crypto_box::aead::rand_core`, and `OsRng` is available via `crypto_box::aead::OsRng`, as is used in the crate's documentation.
=> crypto_box: remove `rand_core` reexport

crypto_box/src/lib.rs
Removes mentions that ChaCha20 supports associated data.
=> crypto_box: documentation improvements

crypto_box/src/lib.rs, crypto_box/src/public_key.rs, crypto_box/src/secret_key.rs, crypto_box/tests/lib.rs
- Moves `seal` to `PublicKey::seal`
- Moves `seal_open` to `SecretKey::unseal`
This should make these slightly more convenient to use by reducing the number of imports required.
=> crypto_box: make `seal` and `unseal` inherent methods

crypto_box/src/lib.rs, crypto_box/src/public_key.rs, crypto_box/src/secret_key.rs
Ensures both types have an infallible `from_bytes` method, a fallible `from_slice` method (which returns `TryFromSliceError` if the length is incorrect), as well as `From`/`TryFrom` impls for 32-byte arrays and slices respectively.
=> crypto_box: consistent constructors for `PublicKey`/`SecretKey`

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml, crypto_box/src/lib.rs
COMPATIBILITY NOTE: previous versions of this crate provided a `ChaChaBox` construction which is incompatible with the one in libsodium. This release makes breaking changes to that construction which provide compatibility with the libsodium implementation. No backwards compatibility is provided for the construction in previous releases of this crate. We apologize for the inconvenience.
- `SEALBYTES` constant ([#81])
- `serde` impl for `SecretKey` ([#101])
- Generic implementation of `CryptoBox` ([#113])
- Use `crypto_secretbox` crate for symmetric cryptography ([#82], [#109])
- Replaced `x25519-dalek` with `curve25519-dalek` v4.0.0-rc; MSRV 1.60 ([#88])
- Use `MontgomeryPoint` as `PublicKey`'s inner type ([#91])
- Make `seal` and `unseal` inherent methods ([#118])
- `seal` => …
=> crypto_box v0.9.0-rc.0

crypto_secretbox/src/lib.rs
There were two nearly identical examples in a row. This removes one of them.
=> crypto_secretbox: remove redundant example

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml, crypto_box/LICENSE-MIT
COMPATIBILITY NOTE: previous versions of this crate provided a `ChaChaBox` construction which is incompatible with the one in libsodium. This release makes breaking changes to that construction which provide compatibility with the libsodium implementation. No backwards compatibility is provided for the construction in previous releases of this crate. We apologize for the inconvenience.
- `SEALBYTES` constant ([#81])
- `serde` impl for `SecretKey` ([#101])
- Generic implementation of `CryptoBox` ([#113])
- Use `crypto_secretbox` crate for symmetric cryptography ([#82], [#109])
- Replaced `x25519-dalek` with `curve25519-dalek` v4; MSRV 1.60 ([#88], [#130])
- Use `MontgomeryPoint` as `PublicKey`'s inner type ([#91])
- Make `seal` and `unseal` inherent methods ([#118])
- `seal` => …
=> crypto_box v0.9.0

Cargo.lock, crypto_kx/Cargo.toml, crypto_kx/src/keypair.rs, crypto_kx/src/keys/secret.rs, crypto_kx/src/lib.rs, crypto_kx/tests/lib.rs
Uses the `CryptoRngCore` trait alias as introduced in `rand_core` v0.6.4.
Also removes extraneous dependencies.
=> crypto_kx: use `CryptoRngCore`; cleanup deps

crypto_kx/CHANGELOG.md
- Use `curve25519-dalek`; MSRV 1.60 ([#89], [#130])
- Use `CryptoRngCore` ([#132])
[#89]: https://github.com/RustCrypto/nacl-compat/pull/89
[#130]: https://github.com/RustCrypto/nacl-compat/pull/130
[#132]: https://github.com/RustCrypto/nacl-compat/pull/132
=> crypto_kx v0.2.0

crypto_secretstream/CHANGELOG.md, crypto_secretstream/Cargo.toml
- Constant corresponding to `crypto_secretstream_xchacha20poly1305_ABYTES` ([#81])
- MSRV 1.60 ([#88])
[#81]: https://github.com/RustCrypto/nacl-compat/pull/81
[#88]: https://github.com/RustCrypto/nacl-compat/pull/88
=> crypto_secretstream v0.2.0

Cargo.lock, crypto_kx/CHANGELOG.md, crypto_kx/Cargo.toml
- docs.rs build (removed bogus `seal` feature)
=> crypto_kx v0.2.1

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_box/src/secret_key.rs, crypto_box/tests/lib.rs
Avoids round tripping `Scalar` to/from bytes when leveraging the `From<Scalar>` impl for `SecretKey`.
=> crypto_box: fix `Scalar` conversion to `SecretKey`

Cargo.lock, crypto_box/CHANGELOG.md, crypto_box/Cargo.toml
- `Scalar` conversion to `SecretKey` ([#137])
[#137]: https://github.com/RustCrypto/nacl-compat/pull/137
=> crypto_box v0.9.1

crypto_box/src/lib.rs
See https://github.com/RustCrypto/stream-ciphers/pull/331
=> Avoid `Clone` bound for the type parameter of `CryptoBox`.

crypto_box/src/lib.rs
In `crypto_secretbox`, there are pub consts we can use.
```
impl<C> SecretBox<C> {
/// Size of an XSalsa20Poly1305 key in bytes
pub const KEY_SIZE: usize = 32;
/// Size of an XSalsa20Poly1305 nonce in bytes
pub const NONCE_SIZE: usize = 24;
/// Size of a Poly1305 tag in bytes
pub const TAG_SIZE: usize = 16;
}
```
Maybe it's better to bring these consts to `crypto_box` too? So we don't have to use magic numbers without import the `crypto_secretbox`.
=> feat(crypto_box): add consts like SecretBox

crypto_box/src/public_key.rs
Derive `Copy` for `crypto_box::PublicKey`.
=> crypto_box: derive `Copy` for `PublicKey`

crypto_box/src/lib.rs, crypto_box/tests/lib.rs, test-vector-gen/src/crypto_box.rs
`crypto_box` currently uses the `*` operator directly to multiply the `secret_key.scalar` and the `public_key.0`.
This results in a minor incompatibility with libsodium, especially for specially drafted public keys.
This MR adds
1.  a test for one such special case, i.e., the public key being on the twist of a curve. Along with this comes the function of generating the ciphertext with libsodium, see `test-vector-gen/src/crypto_box.rs`. This test is taken from [bleichenbacher-daniel/Rooterberg](https://github.com/bleichenbacher-daniel/Rooterberg/blob/979eadc6b2e3868a7fd2afffec14e977adf19f30/test_vectors/nacl_crypto_box/nacl_crypto_box_curve25519_xchacha20_poly1305.json#L2079-L2093).
2. a fix for the Diffie-Hellman computation that essentially copies the code for multiplication from …
=> Fix diffie hellman computation

Cargo.lock, crypto_box/Cargo.toml, crypto_kx/Cargo.toml, crypto_secretbox/Cargo.toml, crypto_secretstream/Cargo.toml
NOTE: this is not intended to have an associated crate release, just to denote that the code on `master` contains breaking changes
Bumps versions to the following:
- `crypto_box` v0.10.0-pre
- `crypto_kx` v0.3.0-pre
- `crypto_secretbox` v0.2.0-pre
- `crypto_secretstream` v0.3.0-pre
=> Bump all version numbers to prereleases

Cargo.lock, crypto_box/Cargo.toml, crypto_kx/Cargo.toml
NOTE: contains breaking changes to the wire format
=> Bump `serdect` to v0.4

crypto_box/src/lib.rs, crypto_box/tests/lib.rs
Uses a name similar to the other constructor
Also places the function after `CryptoBox::new` to give that constructor priority in e.g. rustdoc
=> crypto_box: rename `CryptoBox::new_from_clamped`

crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_kx/Cargo.toml, crypto_kx/src/lib.rs, crypto_secretbox/Cargo.toml, crypto_secretbox/src/lib.rs, crypto_secretstream/Cargo.toml
The former has been removed from the latest `nightly` compiler releases
Also removes the `--cfg docsrs` settings, since they're also automatic
=> Switch from `doc_auto_cfg` to `doc_cfg`
